### ISSUE TITLE
.db file

### ISSUE THREAD

**Issue by woshikevin** [jyungtong/hall-management#1]
Hi, can you provide the user name and passwords for the three users? I would like to try your program

**Comment by jyungtong** [comment]
Hi, thanks for trying my program.

The 3 users and passwords:

tux 123 ,
tan tan ,
gwee wee

Both of them with different roles. Hope you enjoying it.

**Comment by woshikevin** [comment]
hi, thank you very much for the reply. 
I have another request, is it possible for you to decode the database and send to me? 
Just for reference only.

Date: Tue, 18 Jun 2013 23:26:16 -0700

**Comment by jyungtong** [comment]
The database was binary encoded, you may see through the source code on 
how it is read and write.

The dbread and dbwrite class is located at below
https://github.com/tuxtong/hall-management/tree/master/src/main/java/com/ttong/app/objectclass
